### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by linkea131** [helloxz/seafile#1]
If you are OK with the configuration, press [ENTER] to continue.

Generating ccnet configuration in /home/MyCloud/ccnet...

/home/MyCloud/seafile-server/seafile/bin/ccnet-init: error while loading shared libraries: /home/MyCloud/seafile-server/seafile/lib/libsearpc.so.1: file too short

Error occured during setup. 
Please fix possible issues and run the script again.

Error: there is no conf/ directory.
Have you run setup-seafile.sh before this?

**Comment by helloxz** [comment]
您好，此项目已不再维护，建议参考Seafile官方的帮助文档进行安装，感谢支持。
